
export default {
    level: [{
        "value": "ALL",
        "label": "monitoring.evtSeverity.ALL"
    }, {
        "value": "INFO",
        "label": "monitoring.evtSeverity.INFO"
    }, {
        "value": "WARN",
        "label": "monitoring.evtSeverity.WARN"
    }, {
        "value": "ERROR",
        "label": "monitoring.evtSeverity.ERROR"
    }],
    type: [{
        "value": "ALL",
        "label": "monitoring.event.type.ALL"
    }, {
        "value": "SERVER_ONLINE",
        "label": "monitoring.event.type.SERVER_ONLINE"
    }, {
        "value": "SERVER_OFFLINE",
        "label": "monitoring.event.type.SERVER_OFFLINE"
    }, {
        "value": "SERVER_KSVD_START",
        "label": "monitoring.event.type.SERVER_KSVD_START"
    }, {
        "value": "SERVER_KSVD_STOP",
        "label": "monitoring.event.type.SERVER_KSVD_STOP"
    }, {
        "value": "SERVER_KSVD_MSG",
        "label": "monitoring.event.type.SERVER_KSVD_MSG"
    }, {
        "value": "CM_ACTIVE",
        "label": "monitoring.event.type.CM_ACTIVE"
    }, {
        "value": "CM_STANDBY",
        "label": "monitoring.event.type.CM_STANDBY"
    }, {
        "value": "KSVDCMD_RESTART",
        "label": "monitoring.event.type.KSVDCMD_RESTART"
    }, {
        "value": "KSVDCMD_DOWN",
        "label": "monitoring.event.type.KSVDCMD_DOWN"
    }, {
        "value": "KSVDMPCD_RESTART",
        "label": "monitoring.event.type.KSVDMPCD_RESTART"
    }, {
        "value": "KSVDMPCD_DOWN",
        "label": "monitoring.event.type.KSVDMPCD_DOWN"
    }, {
        "value": "KSVDSMARTD_RESTART",
        "label": "monitoring.event.type.KSVDSMARTD_RESTART"
    }, {
        "value": "KSVDSMARTD_DOWN",
        "label": "monitoring.event.type.KSVDSMARTD_DOWN"
    }, {
        "value": "KSVDBRANCHD_RESTART",
        "label": "monitoring.event.type.KSVDBRANCHD_RESTART"
    }, {
        "value": "KSVDBRANCHD_DOWN",
        "label": "monitoring.event.type.KSVDBRANCHD_DOWN"
    }, {
        "value": "DHCPD_RESTART",
        "label": "monitoring.event.type.DHCPD_RESTART"
    }, {
        "value": "DHCPD_DOWN",
        "label": "monitoring.event.type.DHCPD_DOWN"
    }, {
        "value": "KSVDUDPD_RESTART",
        "label": "monitoring.event.type.KSVDUDPD_RESTART"
    }, {
        "value": "KSVDUDPD_DOWN",
        "label": "monitoring.event.type.KSVDUDPD_DOWN"
    }, {
        "value": "KSVDP2P_RESTART",
        "label": "monitoring.event.type.KSVDP2P_RESTART"
    }, {
        "value": "KSVDP2P_DOWN",
        "label": "monitoring.event.type.KSVDP2P_DOWN"
    }, {
        "value": "KSVDCACHEIO_RESTART",
        "label": "monitoring.event.type.KSVDCACHEIO_RESTART"
    }, {
        "value": "KSVDCACHEIO_DOWN",
        "label": "monitoring.event.type.KSVDCACHEIO_DOWN"
    }, {
        "value": "KSVD_NETD_RESTART",
        "label": "monitoring.event.type.KSVD_NETD_RESTART"
    }, {
        "value": "KSVD_NETD_DOWN",
        "label": "monitoring.event.type.KSVD_NETD_DOWN"
    }, {
        "value": "KSVD_DPM_WAKEUP",
        "label": "monitoring.event.type.KSVD_DPM_WAKEUP"
    }, {
        "value": "KSVD_DPM_POWEROFF",
        "label": "monitoring.event.type.KSVD_DPM_POWEROFF"
    }]
}